version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: haxstats
      POSTGRES_USER: haxstats
      POSTGRES_PASSWORD: haxstats
