POST http://localhost:8080/players
Accept: application/json
Content-Type: application/json
Authorization: Basic user e0f64ae0-c7ec-4e3e-b49f-0c1327a7a7f0

{
  "auth": "qwer",
  "name": "player 2"
}


###

POST http://localhost:8080/players
Accept: application/json
Content-Type: application/json
Authorization: Basic user e0f64ae0-c7ec-4e3e-b49f-0c1327a7a7f0

{
"auth": "asdf",
"name": "player 1"
}


###

POST http://localhost:8080/games
Accept: application/json
Content-Type: application/json
Authorization: Basic user e0f64ae0-c7ec-4e3e-b49f-0c1327a7a7f0

{
  "redScore": 5,
  "blueScore": 3,
  "redPossession": 75,
  "bluePossession": 25,
  "winningTeam": "RED",
  "goals": [
    {
      "scoringTeam": "RED",
      "scorerAuth": "asdf",
      "assisterAuth": "qwer",
      "ownGoal": false
    }
  ],
  "playerStats": [
    {
      "playerAuth": "asdf",
      "team": "RED",
      "possession": 37.5,
      "shotsOnGoal": 5,
      "goals": 2,
      "assists": 4,
      "ownGoals": 1,
      "win": 1,
      "loss": 0
    },
    {
      "playerAuth": "qwer",
      "team": "RED",
      "possession": 62.5,
      "shotsOnGoal": 20,
      "goals": 4,
      "assists": 2,
      "ownGoals": 0,
      "win": 1,
      "loss": 0
    }
  ]
}
