spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haxstats
    username: haxstats
    password: haxstats
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: ${USERNAME:user}
      password: ${PASSWORD:}
