spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haxstats
    username: haxstats
    password: haxstats
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: ${USERNAME:user}
      password: ${PASSWORD:}
